
const movieActionTypes  = {
    GET_TRENDING_MOVIES: "GET_TRENDING_MOVIES",
    GET_NETFLIX_ORIGINALS: "GET_NETFLIX_ORIGINALS",
    GET_ROMANCE: 'GET_ROMANCE',
    GET_ACTION: 'GET_ACTION',
    GET_THRILLER: 'GET_THRILLER',
    GET_HORROR: 'GET_HORROR',
    GET_ANIMATION: 'GET_ANIMATION'
}

export default movieActionTypes;